language: objective-c

install:
  - brew install neko haxe
  - mkdir haxelib
  - haxelib setup haxelib

  - haxelib -notimeout install openfl 2.2.1
  - haxelib -notimeout install lime 2.0.1
  - haxelib -notimeout install format

  - git clone --recursive https://github.com/thomasuster/lime.git
  - cd lime
  - git checkout 201
  - cd ..

  - haxelib dev lime lime

  - haxelib run lime rebuild lime
  - haxelib run lime rebuild tools

  - git clone https://github.com/haxenme/nme
  - git clone https://github.com/haxenme/nme-dev
  - git clone https://github.com/haxefoundation/hxcpp
  - haxelib dev nme nme
  - haxelib dev nme-dev nme-dev
  - haxelib dev hxcpp hxcpp

  - cd nme-dev/project
  - neko build.n
  - haxelib run lime rebuild hxcpp
  - haxelib run lime rebuild -Dlegacy

script:
  - openfl test mac